mycart/urls.py
from django.urls import path
from .views import *

app_name ='mycart'
urlpatterns = [
    path('', cart_details,name ='cart_detail'),
    path('add/<int:variant_id>/', add_cart,name='add_cart')

]

shop/urls.py
from django.urls import path
from .views import *
urlpatterns =[
    path('', main_page, name='main_page'),
    path('category/<slug:cat_slug>/',show_category, name='category'),
    path('product/<slug:product_slug>/', detail_product, name='product'),



]

test_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from mycart.views import pageNotFound
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('mycart.urls', namespace='mycart')),
    path('', include('shop.urls')),

]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns =[
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = pageNotFound

shop/models.py
from django.contrib.auth.models import User
from django.db import models
import re
# Create your models here.
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.urls import reverse



class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    text = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='images/%Y/%m')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category',
                                 related_name='products',
                                 on_delete=models.CASCADE)

    sizes = models.ManyToManyField('ClothingSize', through='ProductVariant')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product', args=[self.slug])
class ProductPhotos(models.Model):
    image = models.ImageField(upload_to='images/%Y/%m')
    post = models.ForeignKey('Product', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Фото товара'


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={"cat_slug": self.slug})


class ClothingSize(models.Model):
    size_choices = (
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
    )
    size_name = models.CharField(max_length=2, choices=size_choices, blank=True, null=True)
    class Meta:

        verbose_name = 'Размеры товаров'

    def __str__(self):
        return self.size_name



class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_size = models.ForeignKey(ClothingSize, on_delete=models.CASCADE)
    product_quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product} ({self.product_size}): {self.product_quantity} в наличии"

    class Meta:

        unique_together = ('product', 'product_size')

        verbose_name = 'Кол-во товаров на складе'
        verbose_name_plural = 'Кол-во товаров на складе'




@receiver(pre_delete, sender=Product)
def image_model_delete(sender, instance, **kwargs):
    if instance.image.name:
        instance.image.delete(False)

@receiver(pre_delete, sender=ProductPhotos)
def image_model_delete(sender, instance, **kwargs):
    if instance.image.name:
        instance.image.delete(False)

shop/forms.py
from .models import *
from django import forms

# class SizeForm(forms.ModelForm):
#     class Meta:
#         models =

shop/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Product, Category, ProductPhotos
from .forms import *
from mycart.forms import *
from django.db.models import Q
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from .models import Product
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
# Create your views here.
def main_page(request):
    products = Product.objects.filter(available=True)
    categories = Category.objects.all()

    dict ={

        'products':products,
        'categories':categories,


    }
    return render(request, 'shop/main.html', dict)

def show_category(request, cat_slug):
    products = Product.objects.filter(category__slug=cat_slug)
    categories = Category.objects.all()
    dict = {
        'products': products,
        'categories': categories,
        'cat_selected' : cat_slug,
    }
    return render(request, 'shop/main.html', dict)


def detail_product(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    get_all_photos = ProductPhotos.objects.filter(post=product)
    sizes = product.sizes.all()
    cart_product_form = AddProductInCart(request.POST)
    selected_size = None

    if request.method == 'POST':

        selected_size_id = request.POST.get('size')
        selected_size = get_object_or_404(ClothingSize, id=selected_size_id)
        print(selected_size, product)
    context = {
        'get_all_photos':get_all_photos,
        'product': product,
        'sizes': sizes,
        'cart_product_form':cart_product_form,
        'selected_size': selected_size,
    }

    return render(request, 'shop/details.html', context)

shop/templates/shop/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <title>Мой интернет-магазин одежды</title>
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/styles.css'%}">
    <script type="text/javascript" src="{% static 'shop/js/script.js' %}"></script>

</head>
<body>
<header>
      <h1>Мой интернет-магазин одежды</h1>
      <nav>
        <ul>
            {% for c in categories%}
            {% if c.slug == cat_selected%}
            <h1>{{c.name}}!!!</h1>
            {%else%}
          <li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
            {% endif %}
            {% endfor %}

        </ul>
      </nav>
    </header>
<main>
{% block main%}

{%endblock%}
</main>
<footer>
      <p>&copy; 2023 Мой интернет-магазин одежды</p>
    </footer>
</body>
</html>

shop/templates/shop/details.html
{% extends 'shop/base.html'%}

{% block main%}
<section>
        <div class="img-container">
        <img src="{{ product.image.url}}" width="200" height="100"><br>
        {% for i in get_all_photos%}
                    <img src="{{ i.image.url }}" width="200" height="150" alt="">
                </div>
        {% endfor %}

        <h1>Choose size for {{ product.name }}</h1>
        <form method="POST" id="SizeForm">
        {% csrf_token %}
        <select name="size">
            {% for size in sizes %}
                <option value="{{ size.id }}">
                    {% if selected_size and selected_size.id == size.id %}
                    selected
                    {% endif %}{{ size.get_size_name_display }}</option>
            {% endfor %}
        </select>
    <button type="submit">Select size</button>
</form>





        <h1>Кол-во товара на складе</h1>
        {{products.product_quantity.count}}
        <h2>{{product.name}}</h2>
        <p>{{product.text}}</p>
        <h3>{{product.price}}</h3>

       <div class="input-group my-3" style="width:30%;">
            <input type="number" value="1" class="" id="productQty"/>

            <div class="input-group-append">
                <input type="hidden" class="product-id" value="{{product.id}}">
                <input type="hidden" class="product-title" value="{{product.name}}">
                <button type="button" id="addToCartbtn">Add to Cart</button>
            </div>
        </div>


</section>
<script>
     $("#addToCartbtn").on('click', function(){
                var _qty=$("#productQty").val();
                var _productId=$(".product-id").val();
                var _productName=$(".product-title").val();

                console.log(_qty,_productId,_productName);


    });
</script>
{% endblock%}

shop/templates/shop/main.html
{% extends 'shop/base.html'%}

{% block main%}


<a href="{% url 'mycart:cart_detail' %}"><button>Корзина</button></a>
{% for p in products%}

      <ul class="products">
        <li>


            <img src="{{ p.image.url }}">
          <h3>{{p.name}}</h3>
          <p>{{p.price}}</p>
            <p><a href="{{p.get_absolute_url}}"><button>Подробнее</button></a></p>
        </li>
      </ul>
 {%endfor%}
{% endblock%}